google:
  official_calendar_title: Occupy Richmond Events
  unofficial_calendar_title: Other Activist Events
  username: occupyrichmondva.media@gmail.com
  password: Kanawha2012_
facebook:
  app_id: 261926577206981
  app_secret: c55c84feffe5ac157e054e3cd98727f2
  page_id: 237712702942989
  app_token: AAADuOIiXdsUBAD6pk37Ld5iHM1ZCmLoDCH21jnH8JlJiFJ21Gv6HuqEYDQpBXnOlJ32a7LnxxEGzLxQDuRkG0LJY5kWGdKIrr2tUvZBgZDZD
twitter:
  consumer_key: JZnVhol9SGo2qembTCpWQ
  consumer_secret: 9kpjqUTcDHXfDOFvBaJ0vSXQa1QWMeaDAzNNvPM
  oauth_token: 378850213-l3xo1V7ToLG7q4TO0yPmtrH96kshG7qwWhd48eAC
  oauth_token_secret: kmAYvzoCDgipLrtRotYSSp4KJysfx2kMCHdSP09A00
  
